export const SET_INDEX = 'SET_INDEX'
export const SET_PAUSE = 'SET_PAUSE'
export const SET_RESUME = 'SET_RESUME'
export const FETCH_PICTURES_PENDING = 'FETCH_PICTURES_PENDING'
export const FETCH_PICTURES_FULFILLED = 'FETCH_PICTURES_FULFILLED'
export const FETCH_PICTURES_REJECTED = 'FETCH_PICTURES_REJECTED'


